### ISSUE TITLE
hello i have a bug with the reboot server

### ISSUE THREAD

**Issue by Toriga76** [Devidian/OmegaScripts#1]
Hello .
here is my log.
[2019-08-31 08-40] Server instance:  Tori is going to be restarted!
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Please enter password:
                                         Password incorrect, please enter password:
Password incorrect, please enter password:
           Password incorrect, please enter password:
Password incorrect, please enter password:
    Password incorrect, please enter password:
  Password incorrect, please enter password:
Connection closed by foreign host.
Instance Tori is already running

**Comment by Devidian** [comment]
Hi Tori,

if you have set a telnet password in your config xml it wont work. You only need to set a password when you want to access it from remote. If you dont set a password it will only allow access from local host.

So you can either remove your telnet password or you have to add it to the script login part.

**Comment by Toriga76** [comment]
how can i add him in login part script plz ? sorry i'm begginner .
And thanks for your fast answer.

**Comment by Devidian** [comment]
As my research points out you will have to add a new line at line 41 with a new echo in the brackets that contains the password. I can currently not verify this, sorry! Simple way is to remove the password if you do not use telnet for any remote control.

**Comment by Toriga76** [comment]
yes but i use remote controle via telnet :) 
i try add line41 the password thanks for info and sorry for my bad english :)
have good day.

**Comment by Toriga76** [comment]
ok the connection is good but for the first text he wait the sleep 240 and he say text 1 and text 2 at the same time , and the sleep it's after first text , i don't understand.
Here is my config:
{	        echo ${TEXT[0]};                          (my password) 
		echo ${TEXT[1]};                          (restart 5 min) 
		sleep 240; 
		echo ${TEXT[2]};                           (restart 60sec) 
		sleep 50;
		echo ${TEXT[3]};
		sleep 5;
		echo ${TEXT[4]};
		sleep 5;
		echo 'saveworld';
		sleep 1;
		echo 'shutdown';

and with this code he say 5 min and 60 sec at same time.

**Comment by Toriga76** [comment]
hello you have an idea ?

**Comment by Devidian** [comment]
Sorry for the late answer. I think it should look like this:
But i repeat, i never used telnet with password and i cant verify this!

```
	{	echo "password";
                sleep 2;
                echo ${TEXT[0]};
		sleep 240;
		echo ${TEXT[1]};
		sleep 50;
		echo ${TEXT[2]};
		sleep 5;
		echo ${TEXT[3]};
		sleep 5;
		echo 'saveworld';
		sleep 1;
		echo 'shutdown';
		sleep 1; } | telnet localhost $PORT
```

**Comment by Toriga76** [comment]
thanks for reply :)
in script at "password" 
echo "password"
or
echo password
or 
echo 'password'
i put quote in script or not?

**Comment by Devidian** [comment]
better use quotes ' i think but you just could try it...

**Comment by Toriga76** [comment]
thanks for all
